version: '3.8'

services:
  # MySQL Database
  mysql_database:
    image: mysql:8.0
    container_name: mysql_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: frankenphp
      MYSQL_USER: smt197
      MYSQL_PASSWORD: Serigne197
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Session
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Laravel Application
  app:
    image: laravel-app:latest  # Remplacez par votre image
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      # App Configuration
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: base64:oP9zaoC2J6qUHnfxsOffrIRYtnf7EBZQZfJIfvmv6FE=
      APP_DEBUG: "false"
      APP_URL: http://localhost:8001

      # Database Configuration
      DB_CONNECTION: mysql
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_DATABASE: frankenphp
      DB_USERNAME: smt197
      DB_PASSWORD: Serigne197

      # Redis Configuration
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      # Session & Cache
      SESSION_DRIVER: redis
      CACHE_STORE: redis
      QUEUE_CONNECTION: rabbitmq

      # RabbitMQ Configuration
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      RABBITMQ_VHOST: /

      # Mail Configuration
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Laravel

      # Other configurations
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      OCTANE_SERVER: frankenphp
    volumes:
      - storage_data:/app/storage/app
      - logs_data:/app/storage/logs
    networks:
      - laravel
    depends_on:
      mysql_database:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local
