version: '3.8'

services:
  # Laravel Application uniquement
  app:
    image: your-laravel-image:latest  # Remplacez par votre image
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      # App Configuration
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: base64:oP9zaoC2J6qUHnfxsOffrIRYtnf7EBZQZfJIfvmv6FE=
      APP_DEBUG: "false"
      APP_URL: http://localhost:8001

      # Database Configuration - Utilisez le nom de votre conteneur MySQL existant
      DB_CONNECTION: mysql
      DB_HOST: mysql_database  # Nom de votre conteneur MySQL existant
      DB_PORT: 3306
      DB_DATABASE: frankenphp
      DB_USERNAME: smt197
      DB_PASSWORD: Serigne197

      # Redis Configuration - Utilisez le nom de votre conteneur Redis existant
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis  # Nom de votre conteneur Redis existant
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      # Session & Cache
      SESSION_DRIVER: redis
      CACHE_STORE: redis
      QUEUE_CONNECTION: rabbitmq

      # RabbitMQ Configuration - Utilisez le nom de votre conteneur RabbitMQ existant
      RABBITMQ_HOST: rabbitmq  # Nom de votre conteneur RabbitMQ existant
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin  # Vérifiez vos credentials RabbitMQ
      RABBITMQ_PASSWORD: admin123  # Vérifiez vos credentials RabbitMQ
      RABBITMQ_VHOST: /

      # Mail Configuration
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Laravel

      # Other configurations
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      OCTANE_SERVER: frankenphp
    volumes:
      - storage_data:/app/storage/app
      - logs_data:/app/storage/logs
    networks:
      - bridge  # Réseau par défaut de Docker

volumes:
  storage_data:
    driver: local
  logs_data:
    driver: local

networks:
  bridge:
    external: true  # Utilise le réseau bridge par défaut
